// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGKNmpSnXBstPwzZuq9dvzH_n3imt-ffo',
    appId: '1:697711994101:web:daac7c2762db7a1fef11bc',
    messagingSenderId: '697711994101',
    projectId: 'timekeeper-86ec9',
    authDomain: 'timekeeper-86ec9.firebaseapp.com',
    storageBucket: 'timekeeper-86ec9.firebasestorage.app',
    measurementId: 'G-G4M63L4PEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_0Ni64QA5WhYECROjhET0Rs2zEYD7WHs',
    appId: '1:697711994101:android:c6404d5dba6f24ffef11bc',
    messagingSenderId: '697711994101',
    projectId: 'timekeeper-86ec9',
    storageBucket: 'timekeeper-86ec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDuom4haMLwL8lpVd1LNJAuzx-8On2Bes',
    appId: '1:697711994101:ios:181cc0eb2d58baefef11bc',
    messagingSenderId: '697711994101',
    projectId: 'timekeeper-86ec9',
    storageBucket: 'timekeeper-86ec9.firebasestorage.app',
    iosClientId: '697711994101-g5gk4kumiunjdnvgkra5r9cfoiesmtlo.apps.googleusercontent.com',
    iosBundleId: 'com.leos.timekeeper',
  );
}
